Name: AdventureBot

Version: 1.0

Description: Alexa-based Choose-your-AdventureBot

Parameters:

  - Name: AdventureFile
    Description: Name of the adventure file to use
    Value: my-demo-adventure.yml

  - Name: AdventureBucket
    Description: S3 Bucket for storing adventure assets
    Resource:
      Type: AWS::S3::Bucket
      Allow: ReadWrite

  - Name: AdventureFinishedTopic
    Description: SNS topic to notify when a player finishes an adventure
    Resource:
      Type: AWS::SNS::Topic
      Allow: Publish

  - Name: AdventureFiles
    Description: Package of all adventures files to be uploaded to S3 bucket
    Package:
      Files: assets/adventures/
      Bucket: AdventureBucket
      Prefix: Adventures/

  - Name: SoundFiles
    Description: Package of all sound files to be uploaded to S3 bucket
    Package:
      Files: assets/sounds/*.mp3
      Bucket: AdventureBucket
      Prefix: Sounds/

  - Name: SoundFilesPolicy
    Description: Access policy for sound files in S3 bucket
    Resource:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket:
          Ref: AdventureBucket
        PolicyDocument:
          Statement:
            - Action:
                - "s3:GetObject"
              Effect: Allow
              Resource:
                Fn::Join:
                  - ""
                  - - "arn:aws:s3:::"
                    - Ref: AdventureBucket
                    - "/Sounds/*"
              Principal: "*"

  - Name: PlayerTable
    Description: DynamoDb table for storing player progression in their adventure
    Resource:
      Type: AWS::DynamoDB::Table
      Allow: ReadWrite
      Properties:
        AttributeDefinitions:
          - AttributeName: PlayerId
            AttributeType: S
        KeySchema:
          - AttributeName: PlayerId
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TimeToLiveSpecification:
          AttributeName: Expire
          Enabled: true

Functions:

  - Name: Alexa
    Memory: 128
    Timeout: 30
    Sources:
      # NOTE: Specify your alexa skill id (e.g. amzn1.ask.skill.xxxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx)
      #       to prevent the Lambda function from being invoked by other skills.
      - Alexa: "*"